import type { Classification, ReplayVerdict } from "@/lib/types";

/** One reviewed mistake-tier key moment, distilled to what the summary needs. */
export interface SummaryMistake {
  ply: number;
  moveNumber: number;
  color: "white" | "black";
  san: string;
  classification: Classification;
  concepts: string[];
  confidence: number;
  tags: string[];
  replayVerdict: ReplayVerdict | null;
  thoughts: string;
}

/** Everything needed to generate a whole-game summary, gathered once all key moments are reviewed. */
export interface GameSummaryInput {
  whitePlayer: string;
  blackPlayer: string;
  userColor: "white" | "black";
  result: string;
  terminationReason: string | null;
  totalKeyMoments: number;
  /** MISTAKE / BLUNDER / MISSED_OPPORTUNITY moments, in chronological order. */
  mistakes: SummaryMistake[];
  goodMomentCount: number;
  /** Deterministic ACPL-based rating for this game alone — computed, never invented by an LLM. */
  estimatedRating: number | null;
  /** Tag -> count, across every reflection in this game. */
  tagFrequency: Record<string, number>;
  /** Mistake-tier moments where the player rated their own confidence 4 or 5. */
  highConfidenceMistakeCount: number;
}

export interface StructuredGameSummary {
  /** 2-4 sentences synthesizing the game's key mistakes into a narrative, not a list. */
  narrative: string;
  /** A recurring thinking pattern visible across this game's reflections, or null if there isn't a clear one. */
  recurringPattern: string | null;
  /** Concrete, specific feedback on what to focus on, based on this game. */
  focusAdvice: string;
  /** References confidence ratings/tags where relevant, or null if there's nothing meaningful to say. */
  confidenceObservation: string | null;
  /** Always the deterministically computed value from GameSummaryInput — never regenerated by the provider. */
  estimatedRating: number | null;
}

export interface GameSummaryProvider {
  generateSummary(input: GameSummaryInput): Promise<StructuredGameSummary>;
}
